---
AWSTemplateFormatVersion: '2010-09-09'

Description: API Gateway and Lambda Functions for Hub

Parameters:
  DefS3Bucket:
    Type: String
    Default: lambda-handlers-jina
    Description: Enter S3 Bucket where Lambda function code is uploaded
  HubListLambdaFnS3Key:
    Type: String
    Default: mongoatlas_reader/1/mongoatlas_reader.zip
    Description: Enter S3 Key where Hub List Lambda function code is uploaded
  HubPushLambdaFnS3Key:
    Type: String
    Default: mongoatlas_reader/1/mongoatlas_reader.zip
    Description: Enter S3 Key where Hub List Lambda function code is uploaded
  DefLambdaRole:
    Type: String
    Default: 'arn:aws:iam::416454113568:role/lambda-role'
    Description: Enter IAM role with LambdaAccess
  DeploymentStage:
    Type: String
    Default: dev
    Description: Enter API Gateway stage for deployment
  HubDomain:
    Type: String
    Default: hubapi.jina.ai
    Description: Hub API Endpoint

Resources:
  HubAPI:
    Type: AWS::ApiGateway::RestApi
    Properties:
      ApiKeySourceType: HEADER
      Description: Jina Hub API for bookkeeping
      EndpointConfiguration:
        Types:
          - EDGE
      Name: jina-hub-api
  HubAPIList:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !GetAtt HubAPI.RootResourceId
      PathPart: 'list'
      RestApiId: 
        Ref: HubAPI
  HubAPIListMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      ApiKeyRequired: false
      AuthorizationType: NONE
      HttpMethod: GET
      Integration:
        ConnectionType: INTERNET
        Credentials: !GetAtt HubAPIIAMRole.Arn
        IntegrationHttpMethod: POST
        PassthroughBehavior: WHEN_NO_MATCH
        TimeoutInMillis: 29000
        Type: AWS_PROXY
        Uri: !Sub 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${HubListLambdaFn.Arn}/invocations'
      OperationName: 'HubList'
      ResourceId: 
        Ref: HubAPIList
      RestApiId: 
        Ref: HubAPI
  HubAPIPush:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !GetAtt HubAPI.RootResourceId
      PathPart: 'push'
      RestApiId: 
        Ref: HubAPI
  HubAPIPushMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      ApiKeyRequired: false
      AuthorizationType: NONE
      HttpMethod: POST
      Integration:
        ConnectionType: INTERNET
        Credentials: !GetAtt HubAPIIAMRole.Arn
        IntegrationHttpMethod: POST
        PassthroughBehavior: WHEN_NO_MATCH
        TimeoutInMillis: 29000
        Type: AWS_PROXY
        Uri: !Sub 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${HubPushLambdaFn.Arn}/invocations'
      OperationName: 'HubPush'
      ResourceId: 
        Ref: HubAPIPush
      RestApiId: 
        Ref: HubAPI
  HubAPIModel:
    Type: AWS::ApiGateway::Model
    Properties:
      ContentType: 'application/json'
      RestApiId: 
        Ref: HubAPI
      Schema: {}
  HubAPIStage:
    Type: AWS::ApiGateway::Stage
    Properties:
      DeploymentId: 
        Ref: HubAPIDeployment
      Description: HubAPI Stage v0
      RestApiId: 
        Ref: HubAPI
      StageName: 
        Ref: DeploymentStage
  HubAPIDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn: HubAPIListMethod
    Properties:
      Description: Lambda API Deployment
      RestApiId: 
        Ref: HubAPI
  HubAPIPathMapping:
    DependsOn:
    - HubAPIDeployment
    - HubAPIStage
    Type: AWS::ApiGateway::BasePathMapping
    Properties:
      BasePath: ""
      DomainName:
        Ref: HubDomain
      RestApiId:
        Ref: HubAPI
      Stage:
        Ref: DeploymentStage
  HubAPIIAMRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: ''
            Effect: 'Allow'
            Principal:
              Service:
                - 'apigateway.amazonaws.com'
            Action:
              - 'sts:AssumeRole'
      Path: '/'
      Policies:
        - PolicyName: LambdaAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: 'Allow'
                Action: 'lambda:*'
                Resource: !GetAtt HubListLambdaFn.Arn
              - Effect: 'Allow'
                Action: 'lambda:*'
                Resource: !GetAtt HubPushLambdaFn.Arn
  HubListLambdaFn:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: HubListMongoAtlas
      Description: Hub List Lambda function
      Code:
        S3Bucket: 
          Ref: DefS3Bucket
        S3Key: 
          Ref: HubListLambdaFnS3Key
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      Role: 
        Ref: DefLambdaRole
  HubPushLambdaFn:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: HubPushMongoAtlas
      Description: Hub Push Lambda function
      Code:
        S3Bucket: 
          Ref: DefS3Bucket
        S3Key: 
          Ref: HubPushLambdaFnS3Key
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      Role: 
        Ref: DefLambdaRole
