# This is a basic workflow to help you get started with Actions

name: Hub API CD

on:
  pull_request:
    branches: 
      - master
    types: 
      - closed
    paths: 
      - 'lambda_handlers/*.py'

env:
  GITHUB_PR_NUMBER: ${{github.event.pull_request.number}}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  hub-api-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Prepare Hub List Lambda Deployment Package
        working-directory: ./hub_api_deployment
        run: |
          echo $PWD
          chmod +x prepare_lambda.sh
          bash prepare_lambda.sh --function mongoatlas_reader.py
          
      - name: Prepare Hub Push Lambda Deployment Package
        working-directory: ./hub_api_deployment
        run: |
          chmod +x prepare_lambda.sh
          bash prepare_lambda.sh --function mongoatlas_writer.py
      
      - name: Setup Python
        uses: actions/setup-python@v1
        
      - name: Install dependencies
        working-directory: .
        run : |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        
      - name: Deploy CFN Stack with Lambda functions & API Gateway 
        working-directory: ./hub_api_deployment
        run: |
          python deployment.py --list-deployment-zip mongoatlas_reader.zip --push-deployment-zip mongoatlas_reader.zip --key-id ${GITHUB_PR_NUMBER} --stack-name jinahub-api-stack
          
